INSERT INTO location (INDEX, TYPE, NAME, DEVICE, SN, DESCRIPTION, MAP_URL) VALUES
('LAN_1001', 'LAN', 'Fibonacci conference room',  'switch Linksys LGS116-EU 16x GbE, managed', 'SN11111L', 'first floor, 3rd island on the left from entrance', '/maps/LAN_1001.jpg'),
('LAN_1002', 'LAN', 'DaVinci conference room',    'switch Linksys LGS116-EU 16x GbE, managed', 'SN21111L', 'first floor, 3rd island on the left from entrance', '/maps/LAN_1002.jpg'),
('LAN_1003', 'LAN', 'Canteen',                    'switch Linksys LGS116-EU 16x GbE, managed', 'SN31111L', 'first floor, 3rd island on the left from entrance', '/maps/LAN_1003.jpg'),
('LAN_1004', 'LAN', 'Gaudi conference room',      'switch Linksys LGS116-EU 16x GbE, managed', 'SN41111L', 'first floor, 3rd island on the left from entrance', '/maps/LAN_1004.jpg'),
('LAN_1005', 'LAN', 'Small kitchen SkyBar',       'switch Linksys LGS116-EU 16x GbE, managed', 'SN51111L', 'first floor, 3rd island on the left from entrance', '/maps/LAN_1005.jpg'),
('LAN_1006', 'LAN', 'Fibonacci conference room',  'switch Linksys LGS116-EU 16x GbE, managed', 'SN61111L', 'first floor, 3rd island on the left from entrance', '/maps/LAN_1006.jpg'),
('LAN_1007', 'LAN', 'DaVinci conference room',    'switch Linksys LGS116-EU 16x GbE, managed', 'SN71111L', 'first floor, 3rd island on the left from entrance', '/maps/LAN_1007.jpg'),
('LAN_1008', 'LAN', 'Canteen',                    'switch Linksys LGS116-EU 16x GbE, managed', 'SN81111L', 'first floor, 3rd island on the left from entrance', '/maps/LAN_1008.jpg'),
('LAN_1009', 'LAN', 'Gaudi conference room',      'switch Linksys LGS116-EU 16x GbE, managed', 'SN91111L', 'first floor, 3rd island on the left from entrance', '/maps/LAN_1009.jpg'),
('LAN_1010', 'LAN', 'Small kitchen SkyBar',       'switch Linksys LGS116-EU 16x GbE, managed', 'SN101111L', 'first floor, 3rd island on the left from entrance', '/maps/LAN_1010.jpg'),
('LAN_1011', 'LAN', 'Fibonacci conference room',  'switch Linksys LGS116-EU 16x GbE, managed', 'SN1111111L', 'first floor, 3rd island on the left from entrance', '/maps/LAN_1011.jpg'),
('LAN_1012', 'LAN', 'DaVinci conference room',    'switch Linksys LGS116-EU 16x GbE, managed', 'SN121111L', 'first floor, 3rd island on the left from entrance', '/maps/LAN_1012.jpg'),
('LAN_1013', 'LAN', 'Canteen',                    'switch Linksys LGS116-EU 16x GbE, managed', 'SN131111L', 'first floor, 3rd island on the left from entrance', '/maps/LAN_1013.jpg'),
('LAN_1014', 'LAN', 'Gaudi conference room',      'switch Linksys LGS116-EU 16x GbE, managed', 'SN141111L', 'first floor, 3rd island on the left from entrance', '/maps/LAN_1014.jpg'),
('LAN_1015', 'LAN', 'Small kitchen SkyBar',       'switch Linksys LGS116-EU 16x GbE, managed', 'SN151111L', 'first floor, 3rd island on the left from entrance', '/maps/LAN_1015.jpg'),
('LAN_1016', 'LAN', 'Canteen',                    'switch Linksys LGS116-EU 16x GbE, managed', 'SN131111L', 'first floor, 3rd island on the left from entrance', '/maps/LAN_1016.jpg'),
('LAN_1017', 'LAN', 'Gaudi conference room',      'switch Linksys LGS116-EU 16x GbE, managed', 'SN141111L', 'first floor, 3rd island on the left from entrance', '/maps/LAN_1017.jpg'),
('LAN_1018', 'LAN', 'Small kitchen SkyBar',       'switch Linksys LGS116-EU 16x GbE, managed', 'SN151111L', 'first floor, 3rd island on the left from entrance', '/maps/LAN_1018.jpg'),
('WIFI_1001', 'WIFI', 'Fibonacci conference room', 'access point Ubiquiti UAP-AC-LR UniFi AP, AC Long Range', 'SN11111W', 'first floor, 3rd island on the left from entrance', '/maps/WIFI_1001.jpg'),
('WIFI_1002', 'WIFI', 'DaVinci conference room',  'access point Ubiquiti UAP-AC-LR UniFi AP, AC Long Range', 'SN21111W', 'first floor, 3rd island on the left from entrance', '/maps/WIFI_1002.jpg'),
('WIFI_1003', 'WIFI', 'Canteen',                  'access point Ubiquiti UAP-AC-LR UniFi AP, AC Long Range', 'SN31111W', 'first floor, 3rd island on the left from entrance', '/maps/WIFI_1003.jpg'),
('WIFI_1004', 'WIFI', 'Gaudi conference room',    'access point Ubiquiti UAP-AC-LR UniFi AP, AC Long Range', 'SN41111W', 'first floor, 3rd island on the left from entrance', '/maps/WIFI_1004.jpg'),
('WIFI_1005', 'WIFI', 'Small kitchen SkyBar',     'access point Ubiquiti UAP-AC-LR UniFi AP, AC Long Range', 'SN51111W', 'first floor, 3rd island on the left from entrance', '/maps/WIFI_1005.jpg'),
('WIFI_1006', 'WIFI', 'Fibonacci conference room', 'access point Ubiquiti UAP-AC-LR UniFi AP, AC Long Range', 'SN61111W', 'first floor, 3rd island on the left from entrance', '/maps/WIFI_1006.jpg'),
('WIFI_1007', 'WIFI', 'DaVinci conference room',  'access point Ubiquiti UAP-AC-LR UniFi AP, AC Long Range', 'SN71111W', 'first floor, 3rd island on the left from entrance', '/maps/WIFI_1007.jpg'),
('WIFI_1008', 'WIFI', 'Canteen',                  'access point Ubiquiti UAP-AC-LR UniFi AP, AC Long Range', 'SN81111W', 'first floor, 3rd island on the left from entrance', '/maps/WIFI_1008.jpg'),
('WIFI_1009', 'WIFI', 'Gaudi conference room',    'access point Ubiquiti UAP-AC-LR UniFi AP, AC Long Range', 'SN91111W', 'first floor, 3rd island on the left from entrance', '/maps/WIFI_1009.jpg'),
('WIFI_1010', 'WIFI', 'Small kitchen SkyBar',     'access point Ubiquiti UAP-AC-LR UniFi AP, AC Long Range', 'SN101111W', 'first floor, 3rd island on the left from entrance', '/maps/WIFI_1010.jpg'),
('WIFI_1011', 'WIFI', 'Fibonacci conference room', 'access point Ubiquiti UAP-AC-LR UniFi AP, AC Long Range', 'SN111111W', 'first floor, 3rd island on the left from entrance', '/maps/WIFI_1011.jpg'),
('WIFI_1012', 'WIFI', 'DaVinci conference room',  'access point Ubiquiti UAP-AC-LR UniFi AP, AC Long Range', 'SN121111W', 'first floor, 3rd island on the left from entrance', '/maps/WIFI_1012.jpg'),
('WIFI_1013', 'WIFI', 'Canteen',                  'access point Ubiquiti UAP-AC-LR UniFi AP, AC Long Range', 'SN131111W', 'first floor, 3rd island on the left from entrance', '/maps/WIFI_1013.jpg'),
('WIFI_1014', 'WIFI', 'Gaudi conference room',    'access point Ubiquiti UAP-AC-LR UniFi AP, AC Long Range', 'SN141111W', 'first floor, 3rd island on the left from entrance', '/maps/WIFI_1014.jpg'),
('WIFI_1015', 'WIFI', 'Small kitchen SkyBar',     'access point Ubiquiti UAP-AC-LR UniFi AP, AC Long Range', 'SN151111W', 'first floor, 3rd island on the left from entrance', '/maps/WIFI_1015.jpg'),
('WIFI_1016', 'WIFI', 'Canteen',                  'access point Ubiquiti UAP-AC-LR UniFi AP, AC Long Range', 'SN161111W', 'first floor, 3rd island on the left from entrance', '/maps/WIFI_1016.jpg'),
('WIFI_1017', 'WIFI', 'Gaudi conference room',    'access point Ubiquiti UAP-AC-LR UniFi AP, AC Long Range', 'SN171111W', 'first floor, 3rd island on the left from entrance', '/maps/WIFI_1017.jpg'),
('WIFI_1018', 'WIFI', 'Small kitchen SkyBar',     'access point Ubiquiti UAP-AC-LR UniFi AP, AC Long Range', 'SN181111W', 'first floor, 3rd island on the left from entrance', '/maps/WIFI_1018.jpg');
